### ISSUE TITLE
setup.py has disappeared in version 0.3.0

### ISSUE THREAD

**Issue by yurivict** [jwodder/permutation#2]

**Comment by jwodder** [comment]
Yes, that's intentional.  The project uses PEP 517 now and places all of the project configuration in `setup.cfg`.  Building the project is now done using [build](https://github.com/pypa/build).  Is this a problem for you?  If so, how?

**Comment by yurivict** [comment]
The FreeBSD port doesn't build any more.
I have no idea how to build using ```build``` within the ports framework.

**Comment by yurivict** [comment]
As a part of the FreeBSD package build, I don't need a python-specific package. I need a directory with files as they should be installed. ```setup.py``` did this.

It seems like ```build``` is a semi-new package, existing from Sep-2015, but its homepage https://www.python.org/dev/peps/pep-0517/ says that it is "Provisionally accepted". It doesn't seem to be stable and generally accepted. And I never encountered any other python package that requires it.

**Comment by yurivict** [comment]
Thanks.
