### ISSUE TITLE
Permuation from variable?

### ISSUE THREAD

**Issue by mvnarvaezt** [jwodder/permutation#4]
I dont see a way to create the permuation object from some other variable, like a list or array.  How is it supposed to work with variable input? Or cant it?

**Comment by jwodder** [comment]
In order to pass a list of integers to the `Permutation` constructor, simply use [Python's `*`-prefix operator](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists):

```
>>> image = [5, 4, 3, 6, 1, 2]
>>> Permutation(*image)
permutation.Permutation(5, 4, 3, 6, 1, 2)
```
