### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by VascoSch92** [jwodder/permutation#6]
Hey guys,

very nice packages :-) 

I wanted just to ask why you decided to put everything in the __init__.py.

Wouldn't it be more readable to divide the classes and methods that are contained within into multiple scripts?

**Comment by jwodder** [comment]
The code only defines a single class, along with three helper functions that aren't exported.  You can't split a class across multiple files, and there's practically nothing to be gained from putting the helper functions in a separate file.
